In [1]:
import pandas as pd
from sklearn.metrics import classification_report

In [2]:
!ls

EDA.ipynb                    postproc_train.csv
english_test_with_labels.csv postproc_val.csv
postproc_test.csv

In [3]:
train = pd.read_csv('../Post Processing/data/postproc_train.csv')
val = pd.read_csv('../Post Processing/data/postproc_val.csv')
test = pd.read_csv('../Post Processing/data/postproc_test.csv')
# ref = pd.read_csv('english_test_with_labels.csv')

In [4]:
# label_dic = {'fake':1,'real':0}
# test['enc_label'] = ref.apply(lambda x: label_dic[x['label']], 1)

In [5]:
# test[test.label!=test.enc_label]

Empty DataFrame
Columns: [class0_pred, class1_pred, username_real, username_fake, domain_real, domain_fake, label, enc_label]
Index: []

In [6]:
def post_proc(row):
    if (row['domain_real']>row['domain_fake']) & (row['domain_real']>0.88):
        return 0
    elif (row['domain_real']<row['domain_fake']) & (row['domain_fake']>0.88):
        return 1
    else:
        if (row['username_real']>row['username_fake']) & (row['username_real']>0.88):
            return 0
        elif (row['username_real']<row['username_fake']) & (row['username_fake']>0.88):
            return 1
        else:
            if row['class1_pred']>row['class0_pred']:
                return 1
            elif row['class1_pred']<row['class0_pred']:
                return 0

def post_proc1(row):
    if row['class1_pred']>row['class0_pred']:
        return 1
    elif row['class1_pred']<row['class0_pred']:
        return 0

In [13]:
train['final_pred'] = train.apply(lambda x: post_proc(x), 1)

In [14]:
print(classification_report(train['label'], train['final_pred']))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3360
           1       1.00      1.00      1.00      3060

    accuracy                           1.00      6420
   macro avg       1.00      1.00      1.00      6420
weighted avg       1.00      1.00      1.00      6420

In [15]:
val['final_pred'] = val.apply(lambda x: post_proc(x), 1)

In [16]:
print(classification_report(val['label'], val['final_pred']))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1120
           1       1.00      0.99      0.99      1020

    accuracy                           0.99      2140
   macro avg       0.99      0.99      0.99      2140
weighted avg       0.99      0.99      0.99      2140

In [23]:
from sklearn.metrics import f1_score
f1_score(val['label'], val['final_pred'],average='micro')

0.9911214953271028

In [17]:
test['final_pred'] = test.apply(lambda x: post_proc(x), 1)

In [18]:
print(classification_report(test['label'], test['final_pred']))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1120
           1       1.00      0.98      0.99      1020

    accuracy                           0.99      2140
   macro avg       0.99      0.99      0.99      2140
weighted avg       0.99      0.99      0.99      2140

In [22]:
from sklearn.metrics import f1_score
f1_score(test['label'], test['final_pred'],average='micro')

0.9878504672897196

In [19]:
val[val.final_pred!=val.label]

,class0_pred,class1_pred,username_real,username_fake,domain_real,domain_fake,label,final_pred
61,0.753929,0.246071,0.000000,0.000000,0.000000,0.000000,1,0
757,0.996346,0.003654,0.000000,0.000000,0.000000,0.000000,1,0
1185,0.767392,0.232608,0.000000,0.000000,0.000000,1.000000,0,1
1288,0.294245,0.705755,0.000000,0.000000,1.000000,0.000000,1,0
1312,0.250292,0.749708,1.000000,0.000000,0.838903,0.161097,1,0
1364,0.543479,0.456521,0.000000,0.000000,0.000000,0.000000,1,0
1518,0.581829,0.418171,0.000000,0.000000,0.000000,0.000000,1,0
1521,0.411527,0.588473,0.000000,0.000000,0.000000,0.000000,0,1
1591,0.995330,0.004670,0.026667,0.773333,0.838903,0.161097,1,0
1769,0.420238,0.579762,0.495146,0.004854,0.000000,0.000000,0,1
1790,0.941059,0.058941,0.000000,0.000000,0.000000,0.000000,1,0
1870,0.511586,0.488414,0.000000,0.000000,0.838903,0.161097,1,0
1920,0.918278,0.081722,0.000000,0.000000,0.000000,0.000000,1,0
1930,0.620791,0.379209,0.000000,0.000000,0.000000,0.000000,1,0
1976,0.000559,0.999441,0.000000,0.000000,1.000000,0.000000,1,0
1994,0.761741,0.238259,0.000000,0.000000,0.838903,0.161097,1,0
2004,0.511920,0.488080,0.000000,0.000000,0.000000,0.000000,1,0
2051,0.963755,0.036245,0.000000,0.000000,0.000000,0.000000,1,0
2086,0.750133,0.249867,0.000000,1.000000,0.000000,0.000000,0,1

In [20]:
test[test.final_pred!=test.label]

,class0_pred,class1_pred,username_real,username_fake,domain_real,domain_fake,label,enc_label,final_pred
10,0.732060,0.267940,0.000000,0.000000,0.000000,0.000000,1,1,0
27,0.824448,0.175552,0.000000,0.000000,0.838903,0.161097,1,1,0
102,0.373135,0.626865,0.000000,0.000000,1.000000,0.000000,1,1,0
181,0.343261,0.656739,1.000000,0.000000,0.000000,1.000000,0,0,1
184,0.225028,0.774972,0.000000,0.000000,0.000000,0.000000,0,0,1
267,0.670170,0.329830,0.000000,0.000000,0.000000,0.000000,1,1,0
273,0.502039,0.497961,0.000000,0.000000,0.000000,0.000000,1,1,0
319,0.995932,0.004068,0.000000,0.000000,0.000000,0.000000,1,1,0
349,0.012864,0.987136,0.000000,0.000000,0.000000,0.000000,0,0,1
413,0.778312,0.221688,0.000000,0.000000,0.000000,0.000000,1,1,0
469,0.729116,0.270884,0.000000,0.000000,0.838903,0.161097,1,1,0
650,0.999714,0.000286,0.000000,0.000000,0.000000,1.000000,0,0,1
695,0.545628,0.454372,0.000000,0.000000,0.000000,0.000000,1,1,0
728,0.507567,0.492433,0.000000,0.000000,0.000000,0.000000,1,1,0
827,0.048206,0.951794,0.000000,0.000000,1.000000,0.000000,1,1,0
867,0.804524,0.195476,0.000000,0.000000,0.000000,0.000000,1,1,0
873,0.634749,0.365251,0.000000,0.000000,0.994819,0.005181,1,1,0
928,0.999191,0.000809,0.000000,0.000000,0.000000,1.000000,0,0,1
975,0.512140,0.487860,0.000000,0.000000,0.000000,0.000000,1,1,0
986,0.831067,0.168933,0.000000,0.000000,0.000000,0.000000,1,1,0
1105,0.826940,0.173060,0.000000,0.000000,0.000000,0.000000,1,1,0
1212,0.000389,0.999611,0.962963,0.037037,0.000000,0.000000,1,1,0
1564,0.731947,0.268053,0.000000,0.000000,0.000000,0.000000,1,1,0
1795,0.998827,0.001173,0.000000,0.000000,0.838903,0.161097,1,1,0
1937,0.722304,0.277696,0.000000,0.000000,0.000000,0.000000,1,1,0
2044,0.998893,0.001107,0.000000,0.000000,0.838903,0.161097,1,1,0

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=3, random_state=456)

In [40]:
clf.fit(train.iloc[:,:-2], train.label)

RandomForestClassifier(max_depth=3, random_state=456)

In [41]:
f1_score(val['label'], clf.predict(val.iloc[:,:-2]),average='micro')

0.983177570093458

,class0_pred,class1_pred,username_real,username_fake,domain_real,domain_fake
0,0.999545,0.000455,0.000000,0.000000,0.000000,0.000000
1,0.999419,0.000581,0.000000,0.000000,0.838903,0.161097
2,0.000421,0.999579,0.000000,0.000000,0.000000,1.000000
3,0.999698,0.000302,0.995146,0.004854,0.838903,0.161097
4,0.999704,0.000296,0.000000,0.000000,0.838903,0.161097
...,...,...,...,...,...,...
6415,0.002110,0.997890,0.000000,0.000000,0.000000,0.000000
6416,0.000347,0.999653,0.000000,0.000000,0.000000,0.000000
6417,0.000436,0.999564,0.000000,0.000000,0.000000,0.000000
6418,0.000458,0.999542,0.000000,0.000000,0.000000,0.000000
6419,0.999682,0.000318,0.000000,0.000000,0.000000,0.000000